### ISSUE TITLE
Wrong XML header content-type

### ISSUE THREAD

**Issue by gweihs** [packom/mbus-httpd#3]
Thanks for providing mbus-httpd, which I use with your MBus master hat. Unfortunately the content type of the servers response is text/plain, whereas it should be application/xml to be recognized properly by the requesting software (Home Assistant in my case). If I knew how to build a new version and a new docker container, I could probably fix it myself. Cheers, Gregor

**Comment by packom** [comment]
Thanks for the issue.  The content type varies between application/json and text/plain depending on the API call.

Is there a particular API call or calls that you need to use that Home Assistant requires in application/xml case?  Would application/json work instead?  (Ideally I'd like to maintain consistency with the existing methods that use json.)

**Comment by gweihs** [comment]
Hi, thanks for looking into this. Home Assistant should be able to deal with both XML or JSON. JSON would be preferrable, but either is OK. However it does require the correct header with either. The call I am making is

`curl -v -X POST http://localhost:8080/mbus/get/ttyAMA0/2400/0`

What I am receiving is

`HTTP/1.1 200 OK
x-span-id: 646232ae-653b-46c2-a84e-234f0171f4af
content-type: **text/plain**
content-length: 2372
date: Tue, 04 May 2021 20:44:53 GMT
 
<?xml version="1.0" encoding="ISO-8859-1"?>
<MBusData>

    <SlaveInformation>
        <Id>19127779</Id>
    ...`

So the content-type **text/plain** does not match the actual content, which is **application/xml**. I have tried to look through the code to figure out where it is actually converted to XML. I wasn't sure whether the libmbus functions already return XML or not. I suppose though that the http-response is formed by the server itself, certainly not libmbus, to the matching between the content and the content-type header must occur somewhere else. This is the first time I am looking at RUST code, so it was slow going for me.

Best, Gregor

**Comment by packom** [comment]
Can you try version 0.3.2 of the container (packom/mbus-release:0.3.2).  That uses text/xml as the content-type.  I changed this in 0.3.4, but may revert the change if this works for you.

**Comment by gweihs** [comment]
Excellent, this did the trick, thanks so much! Home Assistant is happy with the XML under the text/xml header, as one can find in the documentation. I read somewhere that text/xml is deprecated, but for this I don't care at all.

**Comment by packom** [comment]
Glad it worked.  I've released 0.3.5 of the container (packom/mbus-release:0.3.5) which is probably a better version to use, as it has other fixes in it.  Let me know if you see any issues with that.

I agree rust has a steep learning curve :-).  In fact the content-type comes from the mbus-api crate which mbus-httpd uses. The API itself is defined here: https://github.com/packom/mbus-api/blob/master/api/openapi.yaml  See line 156 where the content-type for this method is specified.  The majority of the rust code handling the API - including the piece that sets the Content-Type HTTP header - is auto-generated.

To fix the problem therefore required 
- changing the API document
- re-autogenerating and rebuilding mbus-api and publishing a new mbus-api crate
- then rebuilding mbus-httpd to use the new version of mbus-api.
Sounds tedious, but I have CI to handle most of it.

I don't think text/xml is actually deprecated, but can be used interchangeably with application/xml, and applications should handle either.  See RFC 7303 for more details: https://tools.ietf.org/html/rfc7303

**Comment by gweihs** [comment]
Perfect, I pulled the latest image. I had never heard about OpenAPI - this is really neat! 

You are right, text/xml is not deprecated, I read this in a document linked from a post. The document claiming it is deprecated was only a draft  - apparently itself deprecated.

Thanks again for all your help!

**Comment by MaxtonSoftware** [comment]
hi gweihs, I am also trying to use this to pull mbus into HA any chance you could share your setup and how you integrated it into HA? Maybe on the HA forum?

**Comment by gweihs** [comment]
All done, see [this link](https://community.home-assistant.io/t/m-bus-meter-bus-on-raspberry-pi-integration/309467). Let me know if you think anything is missing.
