### ISSUE TITLE
docker on raspi

### ISSUE THREAD

**Issue by manugre** [packom/mbus-httpd#4]
Problem with docker plateforme arch (on pi 2 B) :

sudo docker run --name mbus-httpd   -d -p 8080:8080  -e RUST_LOG=INFO   --device /dev/ttyAMA0:/dev/ttyAMA0    -v /proc/device-tree/hat:/proc/device-tree/hat   --privileged  packom/mbus-release
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

So I had to to sppeficy. But there is a segmentation fault :

sudo docker run --platform linux/arm/armv7l --name mbus-httpd   -d -p 8080:8080  -e RUST_LOG=INFO   --device /dev/ttyAMA0:/dev/ttyAMA0    -v /proc/device-tree/hat:/proc/device-tree/hat   --privileged  packom/mbus-release
Unable to find image 'packom/mbus-release:latest' locally
latest: Pulling from packom/mbus-release
Digest: sha256:87a3774accbbdc7f1625a112011dcb55d143fa4aca0b7f5b14337dda7ccf0a76
Status: Downloaded newer image for packom/mbus-release:latest
d21516363d18c72d506735f02e60ad6a5e83f3620c594b1124f836e6e3124263
docker: Error response from daemon: : signal: segmentation fault (core dumped): unknown.

----
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l GNU/Linux

pi@raspberrypi:~ $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5
...
pi@raspberrypi:~ $ docker --version
Docker version 20.10.6, build 370c289

**Comment by piersfinlayson** [comment]
Can you try this image and let me know your result: packom/mbus-release-arm:latest

Can you also try packom/mbus-release:0.3.4

It sounds like something might have gone wrong with the build/packaging process for the latest build.

**Comment by manugre** [comment]
docker run  --name mbus-httpd   -d -p 8080:8080  -e RUST_LOG=INFO
--device /dev/ttyAMA0:/dev/ttyAMA0    -v
/proc/device-tree/hat:/proc/device-tree/hat   --privileged
 packom/mbus-release-armv7:0.3.4
Unable to find image 'packom/mbus-release-armv7:0.3.4' locally
0.3.4: Pulling from packom/mbus-release-armv7
8cac09a54332: Pull complete
a547965bb539: Pull complete
310e17444815: Pull complete
192330e5b049: Pull complete
22ed6f52392b: Pull complete
Digest:
sha256:530c599c2cd4897a65417e1ea0565a24f1e2df4152341a2f7c1c31e4c41fe158
Status: Downloaded newer image for packom/mbus-release-armv7:0.3.4
WARNING: The requested image's platform (linux/amd64) does not match the
detected host platform (linux/arm/v7) and no specific platform was requested
0f3e008c769a2f0c6bcca213367e6dfc9a4d792dd0a7981fe7b9dcf0cbb6ee4c
docker: Error response from daemon: : signal: segmentation fault (core
dumped): unknown.


And :
 docker run --platform linux/arm/armv7l --name mbus-httpd   -d -p 8080:8080
 -e RUST_LOG=INFO   --device /dev/ttyAMA0:/dev/ttyAMA0    -v
/proc/device-tree/hat:/proc/device-tree/hat   --privileged
 packom/mbus-release:0.3.4
c4f039faabb36c73070bc85c8eee8969edb5ba87edadfcaba56158557fa8698e
docker: Error response from daemon: : signal: segmentation fault (core
dumped): unknown.


I think I have a problem with docker, because the docker "hello word" also
seg faut
06.10.61.42.83


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le ven. 7 mai 2021 à 15:09, Piers Finlayson ***@***.***> a
écrit :

**Comment by packom** [comment]
I'm not able to reproduce the problem - I don't have a Pi 2B to hand, but tested the latest image (0.3.5) on a Pi 3B and Pi Zero and they both work OK.  If you continue to have problems after getting the hello world container running feel free to reopen this issue.

**Comment by manugre** [comment]
I tryed on a fresh raspi 0W;
docker Hello-word (and niinx) are ok;

I still have a segfault (I think) : 
`pi@raspberrypi:~ $ sudo docker run --name mbus  -d -p 8080:8080            -e RUST_LOG=INFO            --device /dev/ttyAMA0:/dev/ttyAMA0            -v /proc/device-tree/hat:/proc/device-tree/hat  --privileged packom/mbus-release
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
00c9f3d19ac1839721b995b6a7f97341a0af37f53303991b643c497af8728103
pi@raspberrypi:~ $ sudo docker ps -a
CONTAINER ID   IMAGE                 COMMAND         CREATED          STATUS                       PORTS     NAMES
00c9f3d19ac1   packom/mbus-release   "/mbus-httpd"   11 seconds ago   Exited (139) 4 seconds ago             mbus
`

**Comment by packom** [comment]
Can you run
```
docker logs --details mbus
```
And upload the logs?

Looks like you might be using a different sort of Raspberry Pi - what type of Pi is this on?

**Comment by manugre** [comment]
it works!
maybe I had a problem with my UART configuration
But I think I had a problem with the ARCH version. I think default install (without specify platform arch) didn't take the good one.

thanks
